### PR TITLE
Do not use SetThreadErrorMode for Vista

### PR DESCRIPTION
**Pull request by jeroen**
Try to fix vista

### CODE REVIEW

**Comment by mati865** [comment]
It'd be easier to build librsvg from a system where Rust runs fine than patch it run on Vista.

**Comment by jeroen** [comment]
I tried that but the resulting binary won't run on vista because it links to SetThreadErrorMode.

**Comment by mati865** [comment]
I've just build librsvg from source and neither libs nor executable reference `SetThreadErrorMode`. It must be coming from some other lib.

Beside that the code you are modifying is internal Rust code. It doesn't propagate to binaries built with Rust.

**Comment by jeroen** [comment]
Holy * you're right, the call is in `libgmodule-2.0.a`.

**Comment by jeroen** [comment]
@mati865 thanks so much for confirming this, I had made completely the wrong diagnosis. The problem was actually glib, not rust.

**Pull request closed without merging**
